[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "dygral"
version = "0.1.0"
description = "Prototype Dynamic / Temporal Graph DSL"

[tool.pytest.ini_options]
minversion = "6.0"
